# Generated by Django 3.1.4 on 2020-12-30 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('raterName', models.CharField(max_length=100)),
                ('date_created', models.DateField(max_length=100)),
                ('grasp_score', models.IntegerField(null=True)),
                ('grip_score', models.IntegerField(null=True)),
                ('pinch_score', models.IntegerField(null=True)),
                ('gross_score', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
