# Generated by Django 3.1.4 on 2020-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='date_created',
            field=models.DateField(default='2020-12-12', max_length=100),
        ),
    ]
